version: '3.3'
services:
  #mongodata:
  #  image: mongo
  #  volumes:
  #    - /data/db
  #  entrypoint: /bin/bash
  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${username}
      MONGO_INITDB_ROOT_PASSWORD: ${pwd}
    #depends_on:
    #  - mongodata
    #volumes_from:
    #  - mongodata
    restart: always
    ports:
      - 27017:27017
  #mongo-express:
    #image: mongo-express
    #depends_on:
      #- mongo
    #ports:
      #- "8081:8081"



  web:
    build: ./
    volumes:
      - ./:/home/node/
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
    external_links:
      - mongo

#networks:
  #nodeapp-network:
    #driver: bridge
