version: '3.8'
services:
  #mongodata:
  #  image: mongo
  #  volumes:
  #    - /data/db
  #  entrypoint: /bin/bash
  mongo:
    image: mongo
    container_name: mongo
    #depends_on:
    #  - mongodata
    #volumes_from:
    #  - mongodata
    restart: always
    ports:
      - 27017:27017
  web:
    build: ./
    depends_on:
      - mongo-express
    volumes:
      - .:/src
      - /src/node_modules
    command: npm run start
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
    external_links:
      - mongo

#networks:
  #nodeapp-network:
    #driver: bridge