version: '3.3'
services:
  mongodata:
    image: mongo
    volumes:
      - /data/db
    entrypoint: /bin/bash
  mongo:
    image: mongo
    container_name: mongo
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD


    #depends_on:
    #  - mongodata
    #volumes_from:
    #  - mongodata
    restart: unless-stopped
    ports:
      - 27017:27017
  #mongo-express:
    #image: mongo-express
    #depends_on:
      #- mongo
    #ports:
      #- "8081:8081"



  web:
    build: ./
    volumes:
      - ./:/home/node/
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
    external_links:
      - mongo

#networks:
  #nodeapp-network:
    #driver: bridge
